Repository oamg/leapp-repository, pull requests merged in 2019-05, with the labels that each got.

#187 HACK: Generate initram disk on the fly
  Makefile
  packaging/leapp-repository.spec
  repos/system_upgrade/el7toel8/actors/copytoboot/actor.py
  repos/system_upgrade/el7toel8/actors/copytoboot/libraries/library.py
  repos/system_upgrade/el7toel8/actors/copytoboot/tests/unit_test.py
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/actor.py
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/85sys-upgrade-redhat/do-upgrade.sh
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/85sys-upgrade-redhat/module-setup.sh
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/90sys-upgrade/initrd-system-upgrade-generator
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/90sys-upgrade/module-setup.sh
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/90sys-upgrade/upgrade.service
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/90sys-upgrade/upgrade.sh
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/90sys-upgrade/upgrade.target
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/dracut/dracut-helpers
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/files/generate-initram.sh
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/libraries/xinitramgen.py
  sources/dracut
Labels: enhancement

#199 rpmscanner: move get_package_repository_data to library
  repos/system_upgrade/el7toel8/actors/rpmscanner/actor.py
  repos/system_upgrade/el7toel8/actors/rpmscanner/libraries/library.py
Labels: bug

#206 Do not traceback when dmi subsystem not available
  repos/system_upgrade/el7toel8/actors/biosdevname/actor.py
Labels: WIP, bug
