Repository oamg/leapp-repository, pull requests merged in 2019-01, with the labels that each got.

#14 Add a doc about actor tests
  docs/tests.md
Labels: documentation

#15 Add best practices doc page
  docs/best-practices.md
Labels: documentation

#9 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#38 Remove test leapp repository
  repos/common/actors/testactor/Makefile
  repos/common/actors/testactor/actor.py
  repos/common/actors/testactor/libraries/private.py
  repos/common/actors/testactor/tests/test_testactor.py
  repos/common/models/test.py
  repos/common/tags/test.py
  repos/common/topics/test.py
  repos/test/.leapp/info
  repos/test/.leapp/leapp.conf
  repos/test/actors/testactor-internal/Makefile
  repos/test/actors/testactor-internal/actor.py
  repos/test/actors/testactor-internal/tests/test_testactor_internal.py
  repos/test/models/test.py
  repos/test/tags/test.py
  repos/test/topics/test.py
Labels: bug

#37 Exclude test file names from naming convention
  CONTRIBUTING.md
Labels: documentation

#4 Add description of phases to the workflow
  repos/system_upgrade/el7toel8/workflows/inplace_upgrade.py
Labels: documentation

#57 Introduce an Inhibitor model
  docs/howto-inhibit-upgrade.md
  repos/system_upgrade/el7toel8/actors/checkbtrfs/actor.py
  repos/system_upgrade/el7toel8/actors/checkbtrfs/tests/test_btrfs.py
  repos/system_upgrade/el7toel8/actors/checkosrelease/actor.py
  repos/system_upgrade/el7toel8/actors/checkosrelease/tests/test_checkosrelease.py
  repos/system_upgrade/el7toel8/actors/checksystemarch/actor.py
  repos/system_upgrade/el7toel8/actors/checksystemarch/tests/test_checksystemarch.py
  repos/system_upgrade/el7toel8/actors/firewalldecision/actor.py
  repos/system_upgrade/el7toel8/actors/firewalldisable/actor.py
  repos/system_upgrade/el7toel8/actors/inhibitwhenluks/actor.py
  repos/system_upgrade/el7toel8/actors/inhibitwhenluks/tests/test_inhibitwhenluks.py
  repos/system_upgrade/el7toel8/actors/osreleasecollector/actor.py
  repos/system_upgrade/el7toel8/actors/verifycheckresults/actor.py
  repos/system_upgrade/el7toel8/actors/verifycheckresults/libraries/report.py
  repos/system_upgrade/el7toel8/models/reports.py
Labels: enhancement
