Repository oamg/leapp-repository, pull requests merged in 2019-09, with the labels that each got.

#325 Improve message on failed submgr cmd
  repos/system_upgrade/el7toel8/libraries/rhsm.py
Labels: enhancement

#320 Make some checks before run targetuserspacecreator dnf operations
  repos/system_upgrade/el7toel8/actors/checkosrelease/actor.py
  repos/system_upgrade/el7toel8/actors/checkosrelease/libraries/library.py
  repos/system_upgrade/el7toel8/actors/dnftransactioncheck/actor.py
  repos/system_upgrade/el7toel8/actors/targetuserspacecreator/actor.py
  repos/system_upgrade/el7toel8/libraries/config/version.py
Labels: bug

#318 Add RelatedResource fields to reports
  repos/system_upgrade/el7toel8/actors/authselectapply/actor.py
  repos/system_upgrade/el7toel8/actors/authselectcheck/actor.py
  repos/system_upgrade/el7toel8/actors/checkacpid/actor.py
  repos/system_upgrade/el7toel8/actors/checkbootavailspace/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkbrltty/actor.py
  repos/system_upgrade/el7toel8/actors/checkbtrfs/actor.py
  repos/system_upgrade/el7toel8/actors/checkchrony/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkdosfstools/actor.py
  repos/system_upgrade/el7toel8/actors/checkfirewalld/actor.py
  repos/system_upgrade/el7toel8/actors/checkgrep/actor.py
  repos/system_upgrade/el7toel8/actors/checkhacluster/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkirssi/actor.py
  repos/system_upgrade/el7toel8/actors/checkmemcached/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checknfs/actor.py
  repos/system_upgrade/el7toel8/actors/checkntp/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkosrelease/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkpostfix/actor.py
  repos/system_upgrade/el7toel8/actors/checkremovedpammodules/actor.py
  repos/system_upgrade/el7toel8/actors/checkrhsmsku/actor.py
  repos/system_upgrade/el7toel8/actors/checksendmail/actor.py
  repos/system_upgrade/el7toel8/actors/checkskippedrepositories/actor.py
  repos/system_upgrade/el7toel8/actors/createresumeservice/actor.py
  repos/system_upgrade/el7toel8/actors/detectgrubconfigerror/actor.py
  repos/system_upgrade/el7toel8/actors/ipuworkflowconfig/libraries/library.py
  repos/system_upgrade/el7toel8/actors/kernel/checkkerneldrivers/actor.py
  repos/system_upgrade/el7toel8/actors/migratebrltty/actor.py
  repos/system_upgrade/el7toel8/actors/migratentp/libraries/library.py
  repos/system_upgrade/el7toel8/actors/opensshalgorithmscheck/actor.py
  repos/system_upgrade/el7toel8/actors/opensshpermitrootlogincheck/actor.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/powertop/actor.py
  repos/system_upgrade/el7toel8/actors/pythoninformuser/actor.py
  repos/system_upgrade/el7toel8/actors/redhatsignedrpmcheck/libraries/library.py
  repos/system_upgrade/el7toel8/actors/removeoldpammodulescheck/actor.py
  repos/system_upgrade/el7toel8/actors/reportleftoverpackages/actor.py
  repos/system_upgrade/el7toel8/actors/reportsettargetrelease/actor.py
  repos/system_upgrade/el7toel8/actors/scheduleselinuxrelabeling/actor.py
  repos/system_upgrade/el7toel8/actors/setpermissiveselinux/actor.py
  repos/system_upgrade/el7toel8/actors/sssdcheck/actor.py
  repos/system_upgrade/el7toel8/actors/storagescanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/tcpwrapperscheck/actor.py
  repos/system_upgrade/el7toel8/actors/vsftpdconfigcheck/libraries/library.py
Labels: Requires Leapp PR

#326 Add missing IPUWorklowTag to PythonInformUser actor
  repos/system_upgrade/el7toel8/actors/pythoninformuser/actor.py
Labels: Requires Leapp PR

#297 Clean to_remove transaction customization file
  etc/leapp/transaction/to_remove
Labels: enhancement

#337 Catch dnf error during RHEL8 userspace creation
  repos/system_upgrade/el7toel8/actors/targetuserspacecreator/libraries/userspacegen.py
Labels: bug

#301 setuptargetrepos actor code cleanup
  repos/system_upgrade/el7toel8/actors/peseventsscanner/actor.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/setuptargetrepos/actor.py
  repos/system_upgrade/el7toel8/actors/setuptargetrepos/tests/test_setuptargetrepos.py
  repos/system_upgrade/el7toel8/actors/targetuserspacecreator/libraries/userspacegen.py
  repos/system_upgrade/el7toel8/actors/usedrepositoriesscanner/actor.py
  repos/system_upgrade/el7toel8/actors/usedrepositoriesscanner/tests/test_usedrepositoriesscanner.py
  repos/system_upgrade/el7toel8/models/repositoriessetuptasks.py
  repos/system_upgrade/el7toel8/models/targetrepositories.py
  repos/system_upgrade/el7toel8/models/usedrepositories.py
Labels: enhancement
