Repository oamg/leapp-repository, pull requests merged in 2019-04, with the labels that each got.

#115 Handle the yum configuration files
  etc/leapp/transaction/to_remove
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/actor.py
  repos/system_upgrade/el7toel8/actors/prepareyumconfig/actor.py
  repos/system_upgrade/el7toel8/tools/handleyumconfig
Labels: enhancement

#132 Py3 after upgrade
  packaging/leapp-el7toel8-deps.spec
  packaging/leapp-repository.spec
  repos/system_upgrade/el7toel8/actors/preparepythonworkround/actor.py
  repos/system_upgrade/el7toel8/workflows/inplace_upgrade.py
  sources/dracut/85sys-upgrade-redhat/do-upgrade.sh
Labels: Requires Leapp PR, enhancement

#142 createresumeservice: Use the Python3 binary
  repos/system_upgrade/el7toel8/actors/createresumeservice/files/leapp_resume.service
Labels: bug

#144 initrdinclude: use replace the -k option by --kver for dracut
  repos/system_upgrade/el7toel8/actors/initrdinclude/actor.py
Labels: bug

#147 Expand check for blacklisted repositories to all actors that use it
  repos/system_upgrade/el7toel8/actors/peseventsscanner/actor.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/tests/unit_test.py
  repos/system_upgrade/el7toel8/actors/repositoriesblacklist/actor.py
  repos/system_upgrade/el7toel8/actors/setuptargetrepos/actor.py
  repos/system_upgrade/el7toel8/actors/setuptargetrepos/tests/test_setuptargetrepos.py
  repos/system_upgrade/el7toel8/models/repositoriesblacklisted.py
Labels: For GA, enhancement

#150 Remove packages depending on redhat-rpm-config + tpm2-abrmd
  etc/leapp/transaction/to_remove
Labels: For GA, enhancement

#141 Do not try to install what's already installed
  repos/system_upgrade/el7toel8/actors/filterrpmtransactionevents/actor.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/actor.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/tests/unit_test.py
  repos/system_upgrade/el7toel8/models/rpmtransactiontasks.py
Labels: For GA, bug

#152 biosdevname: introduce new actor
  repos/system_upgrade/el7toel8/actors/biosdevname/actor.py
  repos/system_upgrade/el7toel8/actors/kernelcmdlineconfig/actor.py
  repos/system_upgrade/el7toel8/models/kernelcmdlineargs.py
Labels: enhancement

#153 persistentnetnamesdisable: introduce new actor
  repos/system_upgrade/el7toel8/actors/kernelcmdlineconfig/actor.py
  repos/system_upgrade/el7toel8/actors/persistentnetnamesdisable/actor.py
Labels: For GA, enhancement

#151 Change the path of Leapp logs and archive the old ones
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  repos/system_upgrade/el7toel8/actors/prepareupgradetransaction/actor.py
  repos/system_upgrade/el7toel8/actors/removeoldlog/actor.py
  repos/system_upgrade/el7toel8/actors/removeoldlog/libraries/library.py
  repos/system_upgrade/el7toel8/actors/removeoldlog/tests/test_removeoldlog.py
  repos/system_upgrade/el7toel8/actors/verifycheckresults/actor.py
  sources/dracut/85sys-upgrade-redhat/do-upgrade.sh
  sources/sos-report/leapp.py
Labels: For GA

#156 Do not allow upgrade without RHEL 8 repos available
  repos/system_upgrade/el7toel8/files/rhel_upgrade.py
Labels: enhancement

#157 Update documentation of upgrade inhibition
  docs/howto-inhibit-upgrade.md
Labels: documentation

#173 Remove squid and python-docs during the upgrade
  etc/leapp/transaction/to_remove
Labels: bug

#175 selinux: fix getting facts
  repos/system_upgrade/el7toel8/actors/systemfacts/libraries/systemfacts.py
  repos/system_upgrade/el7toel8/actors/systemfacts/tests/test_systemfacts_selinux.py
Labels: bug

#178 Do not install python2-docs, python3-docs
  etc/leapp/transaction/to_remove
Labels: bug
