Repository oamg/leapp-repository, pull requests merged in 2019-07, with the labels that each got.

#261 createresumeservice: add deps to prevent race condition
  repos/system_upgrade/el7toel8/actors/createresumeservice/files/leapp_resume.service
Labels: bug

#268 pylint: Extend to test for Python3 compatibility
  .pylintrc
  repos/system_upgrade/el7toel8/actors/checkbootavailspace/libraries/library.py
  repos/system_upgrade/el7toel8/actors/checkbootavailspace/tests/unit_test.py
  repos/system_upgrade/el7toel8/actors/initramdiskgenerator/libraries/initramgen.py
  repos/system_upgrade/el7toel8/actors/migratentp/tests/test_converter.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/rpmtransactionconfigtaskscollector/libraries/scanner.py
  repos/system_upgrade/el7toel8/actors/setuptargetrepos/actor.py
  repos/system_upgrade/el7toel8/libraries/dnfplugin.py
  repos/system_upgrade/el7toel8/libraries/guards.py
  repos/system_upgrade/el7toel8/libraries/mounting.py
  repos/system_upgrade/el7toel8/libraries/overlaygen.py
  repos/system_upgrade/el7toel8/libraries/rhsm.py
  repos/system_upgrade/el7toel8/libraries/utils.py
Labels: WIP

#279 Enable crb <=> the Optional repo is enabled
  repos/system_upgrade/el7toel8/actors/enablecrbrepo/actor.py
  repos/system_upgrade/el7toel8/actors/enablecrbrepo/libraries/library.py
  repos/system_upgrade/el7toel8/actors/enablecrbrepo/tests/test_enablecrbrepo.py
  repos/system_upgrade/el7toel8/actors/peseventsscanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/repositoriesblacklist/actor.py
Labels: enhancement

#271 Add support for fstab entries that do not have optional fields
  repos/system_upgrade/el7toel8/actors/storagescanner/actor.py
  repos/system_upgrade/el7toel8/actors/storagescanner/libraries/library.py
  repos/system_upgrade/el7toel8/actors/storagescanner/tests/files/fstab
  repos/system_upgrade/el7toel8/actors/storagescanner/tests/files/invalid_fstab
  repos/system_upgrade/el7toel8/actors/storagescanner/tests/unit_test.py
Labels: bug

#281 linter: enable invalid-name check
  .pylintrc
Labels: WIP, enhancement

#287 Move documentation to Read the Docs.
  docs/README.md
  docs/best-practices.md
  docs/dependencies.md
  docs/howto-inhibit-upgrade.md
  docs/tests.md
Labels: Requires Leapp PR, documentation
