Repository oamg/leapp-repository, pull requests merged in 2021-02, with the labels that each got.

#642 Bump the required framework version regarding reporting.Key
  packaging/leapp-repository.spec
Labels: Requires Leapp PR

#639 Check the FSTAB file for the deprecated / removed XFS mount options.
  repos/system_upgrade/el7toel8/actors/checkfstabxfsoptions/actor.py
  repos/system_upgrade/el7toel8/actors/checkfstabxfsoptions/libraries/checkfstabxfsoptions.py
  repos/system_upgrade/el7toel8/actors/checkfstabxfsoptions/tests/test_checkfstabxfsoptions.py
Labels: bug

#643 Release 0.13.0
  packaging/leapp-repository.spec
Labels: WIP
