Repository oamg/leapp-repository, pull requests merged in 2022-08, with the labels that each got.

#939 change the default upgrade path for HANA to 8.6
  repos/system_upgrade/common/files/upgrade_paths.json
Labels: sap

#934 BZ#2111835 - move PostgreSQL data content individually
  repos/system_upgrade/el7toel8/actors/satellite_upgrade_data_migration/actor.py
Labels: bug

#937 Fix swap page size during el8toel9 upgrade on aarch64
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/do-upgrade.sh
Labels: bug

#927 Changes around root_scanner to accommodate with non-utf8 filenames
  packaging/leapp-repository.spec
  repos/system_upgrade/common/actors/checkrootsymlinks/actor.py
  repos/system_upgrade/common/actors/checkrootsymlinks/tests/unit_test_checkrootsymlinks.py
  repos/system_upgrade/common/actors/rootscanner/actor.py
  repos/system_upgrade/common/models/rootdirectory.py
Labels: bug

#922 sssd: Fix sssd startup problem due to cache files
  repos/system_upgrade/el7toel8/actors/sssd_handle_cache_files/actor.py
  repos/system_upgrade/el7toel8/actors/sssd_handle_cache_files/libraries/sssd_cache_files.py
  repos/system_upgrade/el7toel8/actors/sssd_handle_cache_files/tests/unit_test_sssd_handle_cache_files.py
Labels: bug, changelog-checked

#919 Update LsblkEntry (StorageInfo) and fix the vdo scanner
  repos/system_upgrade/common/actors/inhibitwhenluks/tests/test_inhibitwhenluks.py
  repos/system_upgrade/common/actors/storagescanner/libraries/storagescanner.py
  repos/system_upgrade/common/actors/storagescanner/tests/unit_test_storagescanner.py
  repos/system_upgrade/common/models/storageinfo.py
  repos/system_upgrade/el8toel9/actors/vdoconversionscanner/libraries/vdoconversionscanner.py
  repos/system_upgrade/el8toel9/actors/vdoconversionscanner/tests/unit_test_vdoconversionscanner.py
Labels: bug

#925 selinux: Improve importing customizations
  repos/system_upgrade/common/actors/selinux/selinuxapplycustom/actor.py
  repos/system_upgrade/common/actors/selinux/selinuxapplycustom/tests/component_test_selinuxapplycustom.py
  repos/system_upgrade/common/actors/selinux/selinuxcontentscanner/libraries/selinuxcontentscanner.py
  repos/system_upgrade/common/actors/selinux/selinuxcontentscanner/tests/unit_test_selinuxcontentscanner.py
Labels: bug

#952 Packaging: Update leapp-repository deps for RHEL 8+
  packaging/leapp-el7toel8-deps.spec
  packaging/leapp-repository.spec
Labels: bug

#953 # Release 0.17.0
  packaging/leapp-repository.spec
Labels: changelog-checked
