Repository oamg/leapp-repository, pull requests merged in 2022-09, with the labels that each got.

#961 CheckVDO: Ask user only faiulres and undetermined devices
  repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
  repos/system_upgrade/el8toel9/actors/checkvdo/libraries/checkvdo.py
  repos/system_upgrade/el8toel9/actors/checkvdo/tests/unit_test_checkvdo.py
Labels: bug, changelog-checked

#965 Make shellcheck happy again
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/do-upgrade.sh
Labels: changelog-checked

#963 actor: firewalld: support 0.8.z
  repos/system_upgrade/el8toel9/actors/firewalldcollectusedobjectnames/libraries/private_firewalldcollectusedobjectnames.py
  repos/system_upgrade/el8toel9/actors/firewalldcollectusedobjectnames/tests/unit_test_firewalldcollectusedobjectnames.py
Labels: bug

#971 firewalldcheckallowzonedrifting: Fix the remediation cmd
  repos/system_upgrade/el8toel9/actors/firewalldcheckallowzonedrifting/actor.py
Labels: bug
