Repository oamg/leapp-repository, pull requests merged in 2022-11, with the labels that each got.

#959 Provide common information about systemd
  repos/system_upgrade/common/actors/systemd/checksystemdservicetasks/libraries/checksystemdservicetasks.py
  repos/system_upgrade/common/actors/systemd/scansystemdsource/actor.py
  repos/system_upgrade/common/actors/systemd/scansystemdsource/libraries/scansystemdsource.py
  repos/system_upgrade/common/actors/systemd/scansystemdsource/tests/test_scansystemdsource.py
  repos/system_upgrade/common/actors/systemd/scansystemdtarget/actor.py
  repos/system_upgrade/common/actors/systemd/scansystemdtarget/libraries/scansystemdtarget.py
  repos/system_upgrade/common/actors/systemd/scansystemdtarget/tests/test_scansystemdtarget.py
  repos/system_upgrade/common/libraries/systemd.py
  repos/system_upgrade/common/libraries/tests/00-test.preset
  repos/system_upgrade/common/libraries/tests/01-test.preset
  repos/system_upgrade/common/libraries/tests/05-invalid.preset
  repos/system_upgrade/common/libraries/tests/test_systemd.py
  repos/system_upgrade/common/libraries/tests/test_systemd_files/abc.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/example.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/example.socket
  repos/system_upgrade/common/libraries/tests/test_systemd_files/extra.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/globbed-one.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/globbed-two.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/template2@.service
  repos/system_upgrade/common/libraries/tests/test_systemd_files/template@.service
  repos/system_upgrade/common/models/systemd.py
  repos/system_upgrade/common/models/systemdservices.py
Labels: enhancement

#979 Support IPU using a target RHEL installation ISO image
  Makefile
  commands/preupgrade/__init__.py
  commands/upgrade/__init__.py
  commands/upgrade/util.py
  packaging/leapp-el7toel8-deps.spec
  packaging/leapp-repository.spec
  repos/system_upgrade/common/actors/checktargetiso/actor.py
  repos/system_upgrade/common/actors/checktargetiso/libraries/check_target_iso.py
  repos/system_upgrade/common/actors/checktargetiso/tests/test_check_target_iso.py
  repos/system_upgrade/common/actors/createisorepofile/actor.py
  repos/system_upgrade/common/actors/createisorepofile/libraries/create_iso_repofile.py
  repos/system_upgrade/common/actors/dnfdryrun/actor.py
  repos/system_upgrade/common/actors/dnfpackagedownload/actor.py
  repos/system_upgrade/common/actors/dnftransactioncheck/actor.py
  repos/system_upgrade/common/actors/initramfs/mounttargetiso/actor.py
  repos/system_upgrade/common/actors/initramfs/mounttargetiso/libraries/mount_target_iso.py
  repos/system_upgrade/common/actors/initramfs/upgradeinitramfsgenerator/actor.py
  repos/system_upgrade/common/actors/initramfs/upgradeinitramfsgenerator/libraries/upgradeinitramfsgenerator.py
  repos/system_upgrade/common/actors/localreposinhibit/actor.py
  repos/system_upgrade/common/actors/localreposinhibit/tests/test_unit_localreposinhibit.py
  repos/system_upgrade/common/actors/scantargetiso/actor.py
  repos/system_upgrade/common/actors/scantargetiso/libraries/scan_target_os_iso.py
  repos/system_upgrade/common/actors/scantargetiso/tests/test_scan_target_iso.py
  repos/system_upgrade/common/actors/targetuserspacecreator/actor.py
  repos/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py
  repos/system_upgrade/common/actors/targetuserspacecreator/tests/unit_test_targetuserspacecreator.py
  repos/system_upgrade/common/libraries/dnfplugin.py
  repos/system_upgrade/common/libraries/mounting.py
  repos/system_upgrade/common/models/upgradeiso.py
Labels: changelog-checked

#984 Fix the check of memory (RAM) limits
  repos/system_upgrade/common/actors/checkmemory/libraries/checkmemory.py
Labels: bug
