Repository oamg/leapp-repository, pull requests merged in 2022-01, with the labels that each got.

#783 Require leapp-framework >= 2.1
  packaging/leapp-repository.spec
Labels: Requires Leapp PR

#788 Bump leapp-framework-dependencies to 4
  packaging/leapp-el7toel8-deps.spec
Labels: Requires Leapp PR

#795 Bump leapp-framework-dependencies to 5
  packaging/leapp-el7toel8-deps.spec
Labels: Requires Leapp PR

#672 The Modularity integration
  repos/system_upgrade/common/actors/filterrpmtransactionevents/actor.py
  repos/system_upgrade/common/actors/filterrpmtransactionevents/tests/test_filterrpmtransactionevents.py
  repos/system_upgrade/common/actors/getenabledmodules/actor.py
  repos/system_upgrade/common/actors/peseventsscanner/actor.py
  repos/system_upgrade/common/actors/peseventsscanner/libraries/peseventsscanner.py
  repos/system_upgrade/common/actors/peseventsscanner/tests/files/sample04.json
  repos/system_upgrade/common/actors/peseventsscanner/tests/unit_test_peseventsscanner.py
  repos/system_upgrade/common/actors/storagescanner/libraries/storagescanner.py
  repos/system_upgrade/common/actors/storagescanner/tests/unit_test_storagescanner.py
  repos/system_upgrade/common/files/rhel_upgrade.py
  repos/system_upgrade/common/libraries/config/version.py
  repos/system_upgrade/common/libraries/dnfplugin.py
  repos/system_upgrade/common/libraries/module.py
  repos/system_upgrade/common/libraries/persistentnetnames.py
  repos/system_upgrade/common/libraries/tests/test_dnfplugin.py
  repos/system_upgrade/common/libraries/tests/test_persistentnetnames_library.py
  repos/system_upgrade/common/libraries/tests/test_utils_logging_handler.py
  repos/system_upgrade/common/libraries/utils.py
  repos/system_upgrade/common/models/module.py
  repos/system_upgrade/common/models/rpmtransactiontasks.py
  repos/system_upgrade/el7toel8/actors/repositoriesblacklist/libraries/repositoriesblacklist.py
  repos/system_upgrade/el7toel8/actors/repositoriesblacklist/tests/test_repositoriesblacklist.py
Labels: enhancement

#696 Control leapp report format
  commands/preupgrade/__init__.py
  commands/upgrade/__init__.py
  commands/upgrade/util.py
Labels: Requires Leapp PR

#780 Now support N and N-1 for real
  commands/command_utils.py
  repos/system_upgrade/common/files/upgrade_paths.json
Labels: IntegrationTestsMissing

#732 Add sssd el8toel9 actor
  repos/system_upgrade/el8toel9/actors/sssdcheck/actor.py
  repos/system_upgrade/el8toel9/actors/sssdfacts/actor.py
  repos/system_upgrade/el8toel9/actors/sssdfacts/libraries/sssdfacts8to9.py
  repos/system_upgrade/el8toel9/actors/sssdfacts/tests/unit_test_sssdfacts_8to9.py
  repos/system_upgrade/el8toel9/models/sssd.py
Labels: IntegrationTestsMissing

#804 modularity: Handle missing modulestream_maps
  repos/system_upgrade/common/actors/peseventsscanner/libraries/peseventsscanner.py
  repos/system_upgrade/common/actors/peseventsscanner/tests/files/sample04.json
  repos/system_upgrade/common/actors/peseventsscanner/tests/unit_test_peseventsscanner.py
Labels: WIP
