Repository oamg/leapp-repository, pull requests merged in 2023-02, with the labels that each got.

#1027 Handle possible failures of xfs_info command
  repos/system_upgrade/common/actors/xfsinfoscanner/libraries/xfsinfoscanner.py
  repos/system_upgrade/common/actors/xfsinfoscanner/tests/unit_test_xfsinfoscanner.py
Labels: bug

#1026 pes_events_scanner: Fix regression in pes_event_parsing
  repos/system_upgrade/common/actors/peseventsscanner/libraries/pes_event_parsing.py
  repos/system_upgrade/common/actors/peseventsscanner/tests/test_event_parsing.py
Labels: changelog-checked

#1030 Actor for RoCE Detection to inhibit IPU
  repos/system_upgrade/el8toel9/actors/rocecheck/actor.py
  repos/system_upgrade/el8toel9/actors/rocecheck/libraries/rocecheck.py
  repos/system_upgrade/el8toel9/actors/rocecheck/tests/unit_test_rocecheck.py
  repos/system_upgrade/el8toel9/actors/rocescanner/actor.py
  repos/system_upgrade/el8toel9/actors/rocescanner/libraries/rocescanner.py
  repos/system_upgrade/el8toel9/actors/rocescanner/tests/unit_test_rocescanner.py
  repos/system_upgrade/el8toel9/models/roce.py
Labels: enhancement

#1041 fix migration of sendmail configs after the upgrade
  repos/system_upgrade/el7toel8/actors/migratesendmail/actor.py
Labels: changelog-checked
