Repository oamg/leapp-repository, pull requests merged in 2023-08, with the labels that each got.

#1090 Preupgrade fails with a devtmpfs entry in fstab
  repos/system_upgrade/common/libraries/overlaygen.py
Labels: bug

#1103 overlay lib: Secure the creation of a disk image when size is < 130
  repos/system_upgrade/common/libraries/overlaygen.py
Labels: changelog-checked

#1117 updategrubcore: Skip on IBM Z systems and cover non-grub2 systems in general
  repos/system_upgrade/common/actors/updategrubcore/actor.py
  repos/system_upgrade/common/actors/updategrubcore/libraries/updategrubcore.py
  repos/system_upgrade/common/actors/updategrubcore/tests/test_updategrubcore.py
  repos/system_upgrade/common/libraries/grub.py
  repos/system_upgrade/common/libraries/tests/test_grub.py
Labels: bug

#1107 Refactor handling of kernel information
  repos/system_upgrade/common/actors/forcedefaultboottotargetkernelversion/actor.py
  repos/system_upgrade/common/actors/forcedefaultboottotargetkernelversion/libraries/forcedefaultboot.py
  repos/system_upgrade/common/actors/forcedefaultboottotargetkernelversion/tests/test_forcedefaultboot_forcedefaultboottotargetkernelversion.py
  repos/system_upgrade/common/actors/initramfs/targetinitramfsgenerator/actor.py
  repos/system_upgrade/common/actors/initramfs/targetinitramfsgenerator/libraries/targetinitramfsgenerator.py
  repos/system_upgrade/common/actors/initramfs/targetinitramfsgenerator/tests/test_targetinitramfsgenerator.py
  repos/system_upgrade/common/actors/ipuworkflowconfig/libraries/ipuworkflowconfig.py
  repos/system_upgrade/common/actors/kernel/checkinstalledkernels/actor.py
  repos/system_upgrade/common/actors/kernel/checkinstalledkernels/libraries/checkinstalledkernels.py
  repos/system_upgrade/common/actors/kernel/checkinstalledkernels/tests/unit_test_checkinstalledkernels.py
  repos/system_upgrade/common/actors/kernelcmdlineconfig/actor.py
  repos/system_upgrade/common/actors/kernelcmdlineconfig/libraries/kernelcmdlineconfig.py
  repos/system_upgrade/common/actors/kernelcmdlineconfig/tests/test_kernelcmdlineconfig.py
  repos/system_upgrade/common/actors/scaninstalledtargetkernelversion/actor.py
  repos/system_upgrade/common/actors/scaninstalledtargetkernelversion/libraries/scankernel.py
  repos/system_upgrade/common/actors/scaninstalledtargetkernelversion/tests/test_scaninstalledkernel_scaninstalledtargetkernelversion.py
  repos/system_upgrade/common/actors/scansourcekernel/actor.py
  repos/system_upgrade/common/actors/scansourcekernel/libraries/scan_source_kernel.py
  repos/system_upgrade/common/libraries/config/tests/test_version.py
  repos/system_upgrade/common/libraries/config/version.py
  repos/system_upgrade/common/libraries/kernel.py
  repos/system_upgrade/common/libraries/tests/test_kernel_lib.py
  repos/system_upgrade/common/libraries/utils.py
  repos/system_upgrade/common/models/installedtargetkernelversion.py
  repos/system_upgrade/common/models/ipuconfig.py
Labels: deprecation

#1116 Use new leapp output apis
  commands/preupgrade/__init__.py
  commands/upgrade/__init__.py
  commands/upgrade/util.py
  packaging/leapp-repository.spec
Labels: Requires Leapp PR
