Repository oamg/leapp-repository, pull requests merged in 2024-04, with the labels that each got.

#1194 pes_events_scanner: override repositories when applying an event
  repos/system_upgrade/common/actors/peseventsscanner/libraries/pes_events_scanner.py
  repos/system_upgrade/common/actors/peseventsscanner/tests/test_pes_event_scanner.py
Labels: changelog-checked

#1206 check_grub_legacy: inhibit when GRUB legacy is present
  repos/system_upgrade/el7toel8/actors/checklegacygrub/actor.py
  repos/system_upgrade/el7toel8/actors/checklegacygrub/libraries/check_legacy_grub.py
  repos/system_upgrade/el7toel8/actors/checklegacygrub/tests/test_check_legacy_grub.py
Labels: enhancement, changelog-checked, report

#1205 Default channel to GA if not specified otherwise
  commands/upgrade/util.py
Labels: bug, changelog-checked

#1207 Enhance grub2 install failure message.
  repos/system_upgrade/common/actors/checkgrubcore/actor.py
Labels: report

#1208 Fix incorrect lscpu command formulation
  repos/system_upgrade/common/actors/scancpu/libraries/scancpu.py
Labels: bug, changelog-checked

#1214 Update reboot msg: Note the console access
  commands/upgrade/__init__.py
Labels: changelog-checked

#1193 Fix kernel cmdline args we add not being propogated to newly installed kernels.
  repos/system_upgrade/common/actors/kernelcmdlineconfig/actor.py
  repos/system_upgrade/common/actors/kernelcmdlineconfig/libraries/kernelcmdlineconfig.py
  repos/system_upgrade/common/actors/kernelcmdlineconfig/tests/test_kernelcmdlineconfig.py
Labels: bug
