Repository oamg/leapp-repository, pull requests merged in 2024-01, with the labels that each got.

#1154 Update dependencies: require xfsprogs and e2fsprogs
  packaging/leapp-repository.spec
  packaging/other_specs/leapp-el7toel8-deps.spec
Labels: bug

#1148 Custom modifications tracking
  repos/system_upgrade/common/actors/checkcustommodifications/actor.py
  repos/system_upgrade/common/actors/checkcustommodifications/libraries/checkcustommodifications.py
  repos/system_upgrade/common/actors/checkcustommodifications/tests/test_checkcustommodifications.py
  repos/system_upgrade/common/actors/scancustommodifications/actor.py
  repos/system_upgrade/common/actors/scancustommodifications/libraries/scancustommodifications.py
  repos/system_upgrade/common/actors/scancustommodifications/tests/test_scancustommodifications.py
  repos/system_upgrade/common/models/custommodifications.py
Labels: report

#1160 Fix _copy_decouple() for relative symlinks
  repos/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py
  repos/system_upgrade/common/actors/targetuserspacecreator/tests/unit_test_targetuserspacecreator.py
Labels: bug, changelog-checked

#1137 support rhel 8 upgrade to 9 on alibaba cloud
  repos/system_upgrade/common/libraries/rhui.py
Labels: changelog-checked

#1120 load data files: update hints in error msgs and ignore the download by default
  repos/system_upgrade/common/actors/checkconsumedassets/libraries/check_consumed_assets.py
  repos/system_upgrade/common/actors/loaddevicedriverdeprecationdata/libraries/deviceanddriverdeprecationdataload.py
  repos/system_upgrade/common/actors/peseventsscanner/libraries/pes_event_parsing.py
  repos/system_upgrade/common/actors/repositoriesmapping/libraries/repositoriesmapping.py
  repos/system_upgrade/common/libraries/fetch.py
Labels: bug, changelog-checked

#1166 Fix another cornercase with symlink handling
  repos/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py
  repos/system_upgrade/common/actors/targetuserspacecreator/tests/unit_test_targetuserspacecreator.py
Labels: bug

#1172 repomap: Add RHEL8 aarch64 repos for Alibaba RHUI
  etc/leapp/files/repomap.json
Labels: changelog-checked
