Repository oamg/leapp-repository, pull requests merged in 2024-05, with the labels that each got.

#1218 mount /usr: Implement try-sleep loop (SAN + FC)
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
Labels: bug

#1219 storage initialisation: apply sleep always
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
Labels: bug

#1235 report which OS release was detected as unsupported
  repos/system_upgrade/common/actors/checkosrelease/libraries/checkosrelease.py
  repos/system_upgrade/common/actors/checkosrelease/tests/test_checkosrelease.py
Labels: report

#1233 drop unused packager field from distro metadata
  repos/system_upgrade/common/actors/distributionsignedrpmscanner/libraries/distributionsignedrpmscanner.py
  repos/system_upgrade/common/files/distro/centos/gpg-signatures.json
  repos/system_upgrade/common/files/distro/rhel/gpg-signatures.json
Labels: changelog-checked

#1152 Extend leappdb with more execution information
  commands/upgrade/util.py
Labels: enhancement

#1242 fix some typos spotted by codespell
  .github/workflows/codespell.yml
  repos/system_upgrade/common/actors/selinux/selinuxapplycustom/actor.py
  repos/system_upgrade/common/libraries/overlaygen.py
  repos/system_upgrade/el8toel9/actors/checkcustomnetworkscripts/libraries/customnetworkscripts.py
Labels: changelog-checked

#1243 BZ#2283067 - don't remove Tomcat during Satellite 7to8 upgrade
  repos/system_upgrade/el7toel8/actors/satellite_upgrade_facts/actor.py
Labels: bug, changelog-checked

#1245 Enable IPU path 8.10 -> 9.5
  repos/system_upgrade/common/files/prod-certs/9.5/279.pem
  repos/system_upgrade/common/files/prod-certs/9.5/362.pem
  repos/system_upgrade/common/files/prod-certs/9.5/363.pem
  repos/system_upgrade/common/files/prod-certs/9.5/419.pem
  repos/system_upgrade/common/files/prod-certs/9.5/433.pem
  repos/system_upgrade/common/files/prod-certs/9.5/479.pem
  repos/system_upgrade/common/files/prod-certs/9.5/486.pem
  repos/system_upgrade/common/files/prod-certs/9.5/72.pem
  repos/system_upgrade/common/files/upgrade_paths.json
Labels: changelog-checked

#1231 dnf-plugin-data: sort intput lists
  repos/system_upgrade/common/libraries/dnfplugin.py
Labels: changelog-checked
