Repository oamg/leapp-repository, pull requests merged in 2024-02, with the labels that each got.

#1174 transitionsystemdservicesstates: Do not handle libvirt services on 8->9+
  repos/system_upgrade/common/actors/systemd/transitionsystemdservicesstates/libraries/transitionsystemdservicesstates.py
  repos/system_upgrade/common/actors/systemd/transitionsystemdservicesstates/tests/test_transitionsystemdservicesstates.py
Labels: bug, changelog-checked

#1157 dracut modules: add breakpoints with more consistent names
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/do-upgrade.sh
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/90sys-upgrade/upgrade.sh
Labels: enhancement

#1177 Release 0.20.0
  packaging/leapp-repository.spec
Labels: changelog-checked

#1176 Packit: Drop tests for obsoleted upgrade paths + restructuralisation
  .github/workflows/pr-welcome-msg.yml
  .packit.yaml
Labels: changelog-checked
