Repository oamg/leapp-repository, pull requests merged in 2024-08, with the labels that each got.

#1273 ipa actor: add shortened url for 9-to-10 migration guide
  repos/system_upgrade/common/actors/checkipaserver/libraries/checkipaserver.py
Labels: shortened-urls

#1278 targetuserspacecreator: stop skipping `directory-hash`
  repos/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py
Labels: Requires Leapp PR, changelog-checked

#1287 Add RHEL 10.0 prod-certs
  repos/system_upgrade/common/files/prod-certs/10.0/279.pem
  repos/system_upgrade/common/files/prod-certs/10.0/419.pem
  repos/system_upgrade/common/files/prod-certs/10.0/479.pem
  repos/system_upgrade/common/files/prod-certs/10.0/72.pem
Labels: changelog-checked
