Repository oamg/leapp-repository, pull requests merged in 2025-02, with the labels that each got.

#1342 checkmicroarchitecture: IPU 9 -> 10: report URL for x86_64-v3
  repos/system_upgrade/common/actors/checkmicroarchitecture/libraries/checkmicroarchitecture.py
Labels: report, shortened-urls

#1319 Add Libdb actor
  repos/system_upgrade/el9toel10/actors/libdbcheck/actor.py
  repos/system_upgrade/el9toel10/actors/libdbcheck/libraries/libdbcheck.py
  repos/system_upgrade/el9toel10/actors/libdbcheck/tests/test_libdbcheck.py
Labels: enhancement

#1346 checksaphana: Update link name to upgrade guide
  repos/system_upgrade/common/actors/checksaphana/libraries/checksaphana.py
Labels: report, shortened-urls

#1348 # Release 0.22.0
  README.md
  docs/README.md
  docs/source/conf.py
  docs/source/libraries-and-api/deprecations-list.md
  packaging/leapp-repository.spec
Labels: changelog-checked
