Repository oamg/leapp-repository, pull requests merged in 2025-07, with the labels that each got.

#1394 Point to leapp-repository contribution guidelines
  CONTRIBUTING.md
  README.md
  docs/source/contrib-and-devel-guidelines.md
Labels: documentation

#1398 Read the DNF config by module.py library
  repos/system_upgrade/common/actors/rpmscanner/libraries/rpmscanner.py
  repos/system_upgrade/common/libraries/module.py
Labels: bug

#1401 Disable localpkg_gpgcheck parameter from plugin data
  repos/system_upgrade/common/files/rhel_upgrade.py
Labels: bug

#1335 el8to9: actors: mysql: Add MySQL actor with recommendations
  repos/system_upgrade/el8toel9/actors/mysqlcheck/actor.py
  repos/system_upgrade/el8toel9/actors/mysqlcheck/libraries/mysqlcheck.py
  repos/system_upgrade/el8toel9/actors/mysqlcheck/tests/test_mysqlcheck.py
Labels: enhancement, report

#1396 Fix target version format checks
  commands/command_utils.py
  commands/tests/test_upgrade_paths.py
  commands/upgrade/util.py
Labels: bug, changelog-checked

#1392 Inhibit upgrade on systems with cgroupsv1 on 9to10
  repos/system_upgrade/el9toel10/actors/inhibitcgroupsv1/actor.py
  repos/system_upgrade/el9toel10/actors/inhibitcgroupsv1/libraries/inhibitcgroupsv1.py
  repos/system_upgrade/el9toel10/actors/inhibitcgroupsv1/tests/test_inhibitcgroupsv1.py
Labels: enhancement, report
