Repository oamg/leapp-repository, pull requests merged in 2025-01, with the labels that each got.

#1323 Fix unreadable output in upgrade log
  repos/system_upgrade/common/libraries/mounting.py
Labels: bug

#1324 Remove unmaintained .gitlab-ci.yml config file
  .gitlab-ci.yml
Labels: changelog-checked

#1258 Fix storage scanner parsing error
  repos/system_upgrade/common/actors/storagescanner/libraries/storagescanner.py
Labels: bug

#1329 Use --sysinit when calling vgchange from mount_usr.sh
  repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
Labels: bug

#1326 redhatsignedrpmcheck: Add remediation hint and URL
  repos/system_upgrade/common/actors/redhatsignedrpmcheck/libraries/redhatsignedrpmcheck.py
Labels: enhancement, shortened-urls

#1315 Update postgresqlcheck.py report
  repos/system_upgrade/el8toel9/actors/postgresqlcheck/libraries/postgresqlcheck.py
Labels: changelog-checked, report

#1334 Fix typos in comments to make spellchecker happy
  repos/system_upgrade/common/actors/filterrpmtransactionevents/actor.py
  repos/system_upgrade/common/actors/selinux/selinuxcontentscanner/libraries/selinuxcontentscanner.py
Labels: changelog-checked

#1313 fix(add_upgrade_boot_entry): convert arg list into a tuple
  repos/system_upgrade/common/actors/addupgradebootentry/libraries/addupgradebootentry.py
  repos/system_upgrade/common/actors/addupgradebootentry/tests/unit_test_addupgradebootentry.py
Labels: bug

#1318 Inhibit upgrades with unsupported XFS
  repos/system_upgrade/common/actors/xfsinfoscanner/actor.py
  repos/system_upgrade/common/actors/xfsinfoscanner/libraries/xfsinfoscanner.py
  repos/system_upgrade/common/actors/xfsinfoscanner/tests/unit_test_xfsinfoscanner.py
  repos/system_upgrade/common/models/xfsinfo.py
  repos/system_upgrade/el9toel10/actors/checkoldxfs/actor.py
  repos/system_upgrade/el9toel10/actors/checkoldxfs/libraries/checkoldxfs.py
  repos/system_upgrade/el9toel10/actors/checkoldxfs/tests/test_checkoldxfs.py
Labels: enhancement, changelog-checked, shortened-urls
